apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-dumper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-dumper
  template:
    metadata:
      labels:
        app: go-dumper
    spec:
      containers:
        - name: go-dumper
          image: ghcr.io/casparjones/go-dumper:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENC_KEY
              value: "CHANGE_ME"
